### ISSUE TITLE
Deprecated error warning

### ISSUE THREAD

**Issue by younggrandpa** [humanmade/S3-Uploads#482] opened 2020-12-19 07:18 UTC
Hello,

**PHP Ver:** _PHP 7.4.12_
**WordPress Ver:** _5.6_
**S3-Uploads Ver:** _2.2.2_

The errors below popped up when I was debugging an unrelated plugin that I was working on (_WP_DEBUG was set to true_). This is not a show stopper as such but I thought it might be important for you guys to know. 

> Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/bitnami/apps/xxxxx/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 554
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/bitnami/apps/xxxxx/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 555

I didn't have time to investigate as "S3-Uploads" plugin works just fine. 

Cheers.
YG

**Comment by rubas** [comment] 2020-12-23 08:44
Same here. It started with PHP 7.4.

[Stacktrace](https://sentry.io/share/issue/d5ea4718db4444bb8620d11f43423ee4/)

**Comment by anhducbkhn** [comment] 2021-01-06 03:37
Same here, my php version 7.4.13

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/wp-content/plugins/S3-Uploads/lib/getid3/getid3.php on line 554
--
Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/wp-content/plugins/S3-Uploads/lib/getid3/getid3.php on line 555

I checked getid3 lib, it looks like, they fixed it.

https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L567

```
$this->info['id3v2']['majorversion']  = ord($header[3]);
$this->info['id3v2']['minorversion']  = ord($header[4]);


we should upgrade getid3 lib.

**Comment by rmccue** [comment] 2021-01-06 11:28
Duplicate of #472, see https://github.com/humanmade/S3-Uploads/issues/472#issuecomment-742551228

**Closed by rmccue** 2021-01-06 11:28 UTC
