### ISSUE TITLE
Support for append mode

### ISSUE THREAD

**Issue by johnbillion** [humanmade/S3-Uploads#606] opened 2022-10-18 10:29 UTC
S3 doesn't support append mode, and opening a file via the s3 stream wrapper in append mode (`a` or `a+`) fails silently, and I assume the same applies to `file_put_contents()` when the `FILE_APPEND` flag is used.

One notable functionality that this breaks is the reports in WooCommerce which provides a CSV download feature (for downloading data for orders, customers, etc). When there are more than 100 entries WooCommerce appends rows in batches using append mode. This doesn't work when S3 Uploads is in use and results in a file of zero length.

Would it be possible for the S3 Uploads plugin to handle this with a compatibility layer? For example:

* When a file handle is opened in append mode, download the file in full to a temp directory
* Push the new lines to the end upon each call to `fwrite()`
* Write the file back to S3 upon the call to `fclose()`

**Comment by johnbillion** [comment] 2022-10-18 12:46
cc @Rayhatron

**Comment by johnbillion** [comment] 2022-11-01 10:17
As per Rufaro's investigation, `a` is supported but `a+` isn't.

**Comment by rmccue** [comment] 2022-11-01 11:16
Based on this, looks like a duplicate of https://github.com/humanmade/S3-Uploads/issues/550 so closing out in favour of that; [AWS' docs do not list `a+` as a supported mode](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html#fopen-modes)

**Closed by rmccue** 2022-11-01 11:16 UTC
