### ISSUE TITLE
Wrong path when deleting intermediate images

### ISSUE THREAD

**Issue by ElaHo** [humanmade/S3-Uploads#77] opened 2015-11-24 20:10 UTC
When trying to delete an image from media library I found out that the path is wrong for intermediate images
is trying to delete
`s3://BUCKET/uploads/s3://BUCKET/uploads/2015/11/image-150x150.jpg`
instead of
`s3://BUCKET/uploads/2015/11/image-150x150.jpg`

so goes wrong.

What could be done?
I've seen possibility to add the following to WP path_is_absolute() found in wp-includes/functions.php. So the path from $intermediate_file is accepted as absolute (but not that good idea cause of WPupdates)
```
function path_is_absolute( $path ) {
	if ( preg_match('#^s3:\/\/#', $path) ) // new
	return true; // new
/*
	 * This is definitive if true but fails if $path does not exist or contains
	 * a symbolic link.
	 */
	if ( realpath($path) == $path )
		return true;

	if ( strlen($path) == 0 || $path[0] == '.' )
		return false;
	
	// Windows allows absolute paths like this.
	if ( preg_match('#^[a-zA-Z]:\\\\#', $path) )
		return true;

	// A path starting with / or \ is absolute; anything else is relative.
	return ( $path[0] == '/' || $path[0] == '\\' );
}
```

path_is_absolute() is called from within path_join() wich is called within wp_delete_attachment()

Second possibility in theme:
```
function my_wp_delete_file( $intermediate_file) {
  /* for more info check post.php wp_delete_attachment() */
  if(class_exists( 'S3_Uploads' )){
     if ( preg_match('#^s3:\/\/#', $intermediate_file) ){
       @unlink( $intermediate_file );
     }
  }

  return $intermediate_file;   
}
add_filter('wp_delete_file', 'my_wp_delete_file');
```
So what would be the plugin solution? Instead of core and theme solutions above

**Comment by ElaHo** [comment] 2015-11-26 11:03
Anybody?

**Comment by joehoyle** [comment] 2015-11-27 17:05
Ahh interesting, it's possible this is broken, we should create a unit test for this as a first step

**Comment by chrisvanpatten** [comment] 2015-12-28 20:20
I've also noticed problems with intermediate image sizes not being deleted.

**Comment by joehoyle** [comment] 2016-02-16 20:18
Dupe of #82, thanks for the report :)

**Closed by joehoyle** 2016-02-16 20:18 UTC
