### ISSUE TITLE
Wrong WP plugin version in 3.0.4

### ISSUE THREAD

**Issue by cbspire** [humanmade/S3-Uploads#607] opened 2022-10-26 15:19 UTC
Hi, I updated the plugin but I noticed that inside the `s3-upload.php` file, the version is 3.0.3

[https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php](https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php)

Can you fix it please?
<img width="708" alt="Screenshot 2022-10-26 at 16 19 40" src="https://user-images.githubusercontent.com/6081047/198066724-631077d4-b559-4b3b-b369-de5d6fd495c3.png">

**Comment by grgarside** [comment] 2022-11-05 17:04
Dupe of #605

**Comment by cbspire** [comment] 2022-11-22 20:24
Closed as duplicate (as mentioned before)

**Closed** 2022-11-22 20:24 UTC
