### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leeharding** [humanmade/S3-Uploads#503] opened 2021-04-07 13:04 UTC
Hi @joehoyle — I'd like to use this plugin for a website project that I'm working on, but I can't find anything about licensing here. Could you let me know if that's something you could detail?
Many thanks, Lee

**Comment by rmccue** [comment] 2021-04-07 13:10
Duplicate of #314; S3 Uploads is GPL :)

**Closed by rmccue** 2021-04-07 13:10 UTC
