### ISSUE TITLE
Bypass WP's built in file uploading to get around upload limits

### ISSUE THREAD

**Issue by AaronHolbrook** [humanmade/S3-Uploads#218] opened 2018-01-23 13:16 UTC
WordPress and PHP have limits on file upload sizes. Unfortunately even if you're able to increase that size, some hosts (WPE specifically in this case) institutes a 200mb cap that is unmovable.

If we'd like to allow larger file limits, this plugin seems like it would be a good fit... _almost_. 

The WP Uploader still follows the same uploading rules/limits. 

AWS S3 offers a way around this utilizing JavaScript however: https://aws.amazon.com/blogs/developer/announcing-the-amazon-s3-managed-uploader-in-the-aws-sdk-for-javascript/

Proposed feature request is to utilize the AWS S3 managed uploader in place of WP's to get around file size restrictions and truly upload straight to S3.

**Comment by joehoyle** [comment] 2018-01-23 14:43
Duplicate of https://github.com/humanmade/S3-Uploads/issues/187. We closed this out due to this being out-of-scope. Though they seem "close" together, the way this would work would be very different to the scenario s3 uploads is solving. I'd recommend building a plugin to do specifically what you are asking for.

**Closed by joehoyle** 2018-01-23 14:43 UTC

**Comment by AaronHolbrook** [comment] 2018-01-23 15:38
Thanks for the reference @joehoyle !

Definitely get where you're coming from, and I agree I think this could be it's own plugin.
