### ISSUE TITLE
Add support for Minio

### ISSUE THREAD

**Issue by ikappas** [humanmade/S3-Uploads#139] opened 2016-11-16 18:59 UTC
# Short Description
It would be useful to enable support for [Minio](https://minio.io)

# Description
Minio is an object storage server built for cloud application developers and devops that is compatible with Amazon S3.

As a result Minio should work out of the box with this plugin provided there is a way to change the default `endpoint` configuration variable passed to the Aws\S3\S3Client.

# Suggested Fix
To achieve this requires a minor change  class-s3-uploads.php:162 from:

## From:
```php
$params = array(
    'version' => 'latest'
);
```
## To:
```php
$params = array(
    'version' => 'latest',
    'endpoint' => $this->get_s3_url(),
);
```

or introduce an `S3_UPLOADS_ENDPOINT` constant to be used instead of $this->get_s3_url();

# References
- [Minio](https://minio.io)
- [How to use AWS SDK for PHP with Minio Server](https://docs.minio.io/docs/how-to-use-aws-sdk-for-php-with-minio-server)

**Comment by andrewklau** [comment] 2016-11-16 22:02
You can use minio by passing it to `s3_uploads_s3_client_params`

See https://github.com/humanmade/S3-Uploads/pull/138

**Comment by andrewklau** [comment] 2016-11-17 00:09
@ikappas we use this https://gist.githubusercontent.com/andrewklau/78dddf113947767adb475ca4ad31aea6/raw/3c4aea8d6f0f265fa03e8bebd8f0984056e859aa/s3-uploads-endpoint.php

**Comment by rmccue** [comment] 2016-11-17 00:51
Going to go ahead and close this as a duplicate of #138, as there's already a way to achieve this, **but** we'd love to add this to the docs if you'd like to PR a readme change. :)

**Closed by rmccue** 2016-11-17 00:51 UTC

**Comment by ikappas** [comment] 2016-11-17 09:23
@rmccue @andrewklau  
Thank you for your swift response. 

Isn't S3_UPLOADS_BUCKET_URL the same as endpoint ?

**Comment by andrewklau** [comment] 2016-11-17 09:28
Bucket URL is the URL which is served to the users. So you could use like CloudFront to proxy the requests to S3/Minio, and you'd set that the cloudfront URL as your BUCKET_URL

**Comment by ikappas** [comment] 2016-11-17 09:57
@andrewklau @rmccue 

Thanks for clarifying! 

So wouldn't it make sense to add the `S3_UPLOADS_ENDPOINT_URL` constant in the S3 Uploads plugin in order to simplify the support for Minio and any other third party S3 compatible service?

I think it is self evident that having to configure this plugin in wp-config.php and adding an extra plugin just to filter the parameters in order to make it work is not that user friendly.

**Comment by rmccue** [comment] 2016-11-17 11:24
Using Minio is somewhat outside the scope of this plugin (it's called S3 Uploads, after all), and it's a bit of an edge case. Constants can only be defined once, and are a bit more inflexible than filters, which is why the filter solution is preferred.

Rather than a full plugin, you could also create a [must-use plugin](https://codex.wordpress.org/Must_Use_Plugins) which is a single file with the minimal code to add this filter, and doesn't appear in the admin UI.
