### ISSUE TITLE
Fatal error: Class 'Aws\S3\Sync\UploadSyncBuilder' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-uploadsyncbuilder.php on line 3

### ISSUE THREAD

**Issue by carl-alberto** [humanmade/S3-Uploads#186] opened 2017-07-31 02:45 UTC
I'm attempting to bulk copy my current uploads folder to my s3 bucket and tried to run

`wp s3-uploads upload-directory directory s3://target-bucket/uploads/directory`

but getting

`Fatal error: Class 'Aws\S3\Sync\UploadSyncBuilder' not found in /htdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-uploadsyncbuilder.php on line 3`

`wp s3-uploads migrate-attachments` is working fine but would like to upload a specific folder only so I'm keen on making the` upload-directory` work

using

`WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/opt/bitnami/apps/wordpress/htdocs
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.3.0`

WP version 4.8.1
Ubuntu 14.04.5
Apache 2.4.25

**Comment by jawittdesigns** [comment] 2017-08-25 23:01
I'm getting the same error. It seems like that class is trying to extend a class that is no longer part of the project. 

Is the removal of the `UploadSyncBuilder` class intentional or is the plugin going through some refactoring and all the parts aren't updated yet? 

It's weird, it almost seems like this project has been abandoned, but there's still activity. 

@carl-alberto If you remove the `extends Aws\S3\Sync\UploadSyncBuilder` code from the  `S3_Uploads_UploadSyncBuilder` it seems to work, but I haven't been able to fully test it.

**Comment by coperator** [comment] 2018-01-09 09:28
Duplicate of #100

**Closed** 2018-03-16 01:16 UTC
