### ISSUE TITLE
Image not renamed correctly

### ISSUE THREAD

**Issue by mattheu** [humanmade/S3-Uploads#30] opened 2015-06-27 14:38 UTC
Whilst I remember...
- if you upload an image a second time - it doesn't rename the image file and the WP attachment will appear broken.
- if you have an attachment - and the source file is missing - uploading a new copy will create a new attachment with a broken image and the image will show for the first broken attachment

**Comment by fklein-lu** [comment] 2015-11-16 16:32
@mattheu I tried reproducing those issues, but no luck:
- The image file is correctly renamed (an `-1` is attached to the end of the file name) and both images work.
- When deleting an image in the bucket, and then uploading that same image again, you now have two working attachments with the same image.

Could you please verify whether your issue is solved as well?

**Comment by mattheu** [comment] 2015-11-16 16:57
The first issue - uploading a second time. Tried to reproduce and it appears to be fixed.

> When deleting an image in the bucket, and then uploading that same image again, you now have two working attachments with the same image.

Yes... but the is image showing for the first actually the one attached to the second? What if you then delete the first again?

Not a huge problem TBH... I can't remember how I got into this situation right now! I think it was when activating the plugin on an existing site.

Happy to close if you can't reproduce!

**Comment by fklein-lu** [comment] 2015-11-16 17:15
Could point, so here is the behaviour I observed:
1. I upload an image and then delete the all source file from the S3 bucket: The attachment persists, but all the images (thumbnail, medium, full sizes,...) are broken.
2. I upload a second image with different content, different size, and the same name. This will fix the full display of the first attachment (as the file name is the same) with the new content, but it will break the thumbnail, since the generated size for the preview is different (in my case 300x157 vs 300x209) pixels.
3. Deleting the first attachment deletes the main file on S3, breaking the second attachment's full size display. But the other image sizes are not deleted, since they differ from the original image, so they stay on S3. 

I think that this is how it would work if you were on your local install, without the offloading to S3. So not sure what the plugin could do to work around that.

**Comment by mattheu** [comment] 2015-11-16 17:25
Could you use the post slug to set the filename and ensure it is unique to that attachment?

**Comment by joehoyle** [comment] 2017-12-20 16:24
This isn't unique to this plugin, it would happen to the local filesystem too, therefore I'm going to close this out.

**Closed by joehoyle** 2017-12-20 16:24 UTC
